# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fcc7fe24788ba64123090d9b54479673dfb2bfe24cc057850930c6b63e2f5b3738db4ed34dedddf60405d069fd359f30662d2edb53a57f5a742d4459847a88db

test:
  secret_key_base: 2852ab248ca8b92d083c28fb9523b35ffaa372b4f00cb81b0a1fa4f69522b27f231bd5373e217f3b8d0e5c7a26b0e4113067ffe63f824f198c0170941ca81196

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
